### ISSUE TITLE
打超过四个字的拼音，有问题

### ISSUE THREAD

**Issue by Huandeep** [siuze/ShanRenMaLTS#38]
超过四个字的拼音，比如我要打`三氧化二铝陶瓷股骨头`，打出`san yang hua er`前四个拼音串的时候选中`三氧化二铝陶瓷股骨头`可以直接上屏，但是打出`san yang hua er lv`时，三氧化二铝陶瓷股骨头后面会增加第五个拼音串，无法直接上屏。

```
三氧化二铝	san yang hua er lv	1700
三氧化二铝陶瓷股骨头	san yang hua er lv tao ci gu gu tou	1200
猪免疫球蛋白	zhu mian yi qiu dan bai	1700
猪免疫球蛋白口服液	zhu mian yi qiu dan bai kou fu ye	1200
```

![image](https://user-images.githubusercontent.com/30691481/232426683-fd90f2e5-e09b-4a08-a7d8-99a043ff4f00.png)
![image](https://user-images.githubusercontent.com/30691481/232427477-8dfd259c-d8fd-41a3-a2e1-f956840aa987.png)

**Comment by siuze** [comment]
问题定位在由长词联想获得的候选词选中上屏时，仅会被认为是前四个音节的翻译结果，从而保留之后的部分为未翻译音节。

这个bug需要研究修改librime才能修复。本人近期实在较忙，得空时会考虑对该问题进行处理

**Comment by siuze** [comment]
[修复长词联想功能中上屏词汇与消耗音节数量不匹配的问题 4cca73d](https://github.com/siuze/librime/commit/4cca73d0cdb6a362619bf70645c4abfd80df7416)   
  
上面这个commit应该解决了该问题。
