### ISSUE TITLE
时间反差出现4月0日

### ISSUE THREAD

**Issue by Anber55** [siuze/ShanRenMaLTS#46]
输入D进行时间反差，出现了不存在的4月0日，求大佬修复
<img width="279" alt="截屏2024-06-08 07 09 32" src="https://github.com/siuze/ShanRenMaLTS/assets/117334130/9a31239d-6194-4c35-a25f-be3746a7358e">

**Comment by siuze** [comment]
我排查了一下，日期转换脚本的原作者在通过日期差值推导月份时，似乎对数据索引序号的理解有误， 造成了此bug。   
已提交一版修复 14208be436fc871c85850920670c6a510d4f8465 ，使用20201015-20221224的数据进行检查通过，但不保证别的地方还会有类似的bug，毕竟脚本不是我写的，如有其他问题，请尝试重新开启issue或另外创建新issue。
